#!/bin/bash
## Test Tone Generator
## By marduk191
## email: marduk191@gmail.com

#Set file format for output
tgfmt="wav"
#Audio sample rate
tgfreq="44100"
#set output folder
tgsubdir="output"
#Duration of tracks
tgdur="1"
#Start frequency
tgbegin="1"
#Ending frequency
tgend="50"
#jump multiple
tgmultiple="1"

mkdir $tgsubdir
cd $tgsubdir
echo "Creating 44,100 wave samples"
#from first frequency to end frequency
for (( n="$tgbegin"; n<="$tgend"; n+="$tgmultiple" ))
    do echo "$n Hz">&2
sox -nt "$tgfmt" -r"$tgfreq" -c2 "$n"HZ."$tgfmt" synth "$tgdur" sine $n
done
ls -1v > "$tgsubdir".m3u
